name: load-balancing

services:

  # nginx app
  nginx-app:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - developers
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # fastapi app1
  app1:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: fastapi-app1
    command: >
      bash -c "
        fastapi run app/main.py --host 0.0.0.0 --port 3000
      "
    ports:
      - "3000:3000"
    networks:
      - developers

  # fastapi app2
  app2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi-app2
    command: >
      bash -c "
        fastapi run app/main.py --host 0.0.0.0 --port 4000
      "
    ports:
      - "4000:4000"
    networks:
      - developers

  # fastapi app3
  app3:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: fastapi-app3
    command: >
      bash -c "
        fastapi run app/main.py --host 0.0.0.0 --port 5000
      "
    ports:
      - "5000:5000"
    networks:
      - developers

networks:
  developers:
    driver: bridge
